In [8]:
from scipy.stats import ks_2samp

In [1]:
# ks_2samp  will accept two arrays .

In [2]:
import numpy as np

In [3]:
arr1 = np.arange(10)
arr2 = np.arange(10)

In [4]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
ks_2samp(arr1,arr2)

KstestResult(statistic=0.0, pvalue=1.0)

In [18]:
res1 = ks_2samp(arr1,arr2)

In [19]:
res1.pvalue

1.0

In [20]:
# As pvalue is 1, so it suggest we have to accept Null hypothesis . Null hypothesis suggest that arr1 and arr2 have same distribution .

In [10]:
# If pvalue==1.0 then distribution of arr1 and arr2 will be same .

In [12]:
arr3 = np.arange(10,20)

In [13]:
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
ks_2samp(arr2,arr3)

KstestResult(statistic=1.0, pvalue=1.0825088224469026e-05)

In [15]:
res = ks_2samp(arr2,arr3)

In [16]:
res.pvalue

1.0825088224469026e-05

In [17]:
round(res.pvalue)

0

In [21]:
# Apporximately the pvalue is 0 , so it suggest that Null hypothesis is rejected .

In [22]:
# Null: Two dataset are from same distribution
# Alternate : Two dataset are not from same distribution

""" 
    if p>=0.5 :
        We have sufficient proof that Null hypothesis is True
    else:
        We don't have sufficient proof that Null hypothesis is True
"""

" \n    if p>=0.5 :\n        We have sufficient proof that Null hypothesis is True\n    else:\n        We don't have sufficient proof that Null hypothesis is True\n"

In [23]:
# if we don't have even 5% of proof to accept the Null hypothesis , then we reject the Null hypothesis .